Finished remote configuration

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -17,6 +17,40 @@ case $1 in
 		chown homegear:homegear /var/log/homegear-gateway
 		chmod 750 /var/log/homegear-gateway
 
+		mkdir -p /var/lib/homegear-gateway
+		chown homegear:homegear /var/lib/homegear-gateway
+		chmod 750 /var/lib/homegear-gateway
+
+		uuid=$(cat /proc/sys/kernel/random/uuid)
+		sed -i "s/^#uPnPUDN .*/uPnPUDN = ${uuid}/g" /etc/homegear/gateway.conf
+
+		if test ! -e /var/lib/homegear-gateway/dh.pem; then
+			if [[ $DIALOG_OUTPUT ]]; then
+				platform=$(dpkg --print-architecture)
+				if [[ $platform == "armhf" ]] || [[ $platform == "arm64" ]]; then
+					echo "The generation can take up to 30 minutes."
+				fi
+				openssl dhparam -check -text -5 -out /var/lib/homegear-gateway/dh.pem 1024 > /dev/null 2>&1 &
+				opensslPid=$!
+				exitcode=0
+				counter=0
+				while [[ $exitcode -eq 0 ]]; do
+					kill -0 $opensslPid > /dev/null 2>&1
+					exitcode=$?
+					counter=$((counter+1))
+					if [[ $counter -eq 30 ]]; then
+						counter=0
+						echo "Please wait..."
+					fi
+					sleep 1
+				done
+			else
+				openssl dhparam -check -text -5 -out /var/lib/homegear-gateway/dh.pem 1024
+			fi
+			chown homegear:homegear /var/lib/homegear-gateway/dh.pem
+			chmod 400 /var/lib/homegear-gateway/dh.pem
+		fi
+
 		pidof systemd
 		if [ $? -eq 0 ]; then
 			systemctl enable homegear-gateway.service
